### ISSUE TITLE
Zola calibration output 

### ISSUE THREAD

**Issue by Giabbas** [imodpasteur/ZOLA-3D#10]
Hello,
I’m quite new in using ZOLA-3D, so I apologize if the question may be a bit trivial. 
I’m a bit confused by the output I get in the Calibration phase (ZOLA_calibration_PSF.json).
If I understood correctly, from the paper I would expect the three first Zernike coefficients not to be taken into account, and so to have e.g. Noll’s sequential indices starting from j=4.

In a few words, what do the terms in the output file correspond to? Are they in OSA/ANSI standard indexing? Do they start with j=0 or j=3?

Thank you very much,

**Comment by benoitbenoit** [comment]
Hello,
Sorry for the confusion. you are right: The order is OSA/ANSI. 
In the calibration file, the OSA/ index are indicated to avoid confusion (see "ZernikeCoef" field). 
The three first zernike coefficients are indeed unuseful. That is why their value should be 0 if you look at the calibration file. 

Sometimes, I use tilt (OSA index 1 & 2) inside the calibration program, but it is just to register the beads together with subpixelic precision when many beads are selected in the field of view. So if the value is not 0, you can just ignore it since it has no effect on the shape of the PSF.

Something important that I realized few weeks ago: If you plan to import the calibration file in another program, be careful because "y" axis might be inverted. In imaging (such as in ZOLA-3D) the y axis is oriented to the bottom. But if you render the phase with "plot" function in python for instance, the "y" axis will be oriented to the top. This reverses aberrations of the microscope according to "Y" axis. It is not an error but it is important to know it.
Best,
Benoit Lelandais

**Comment by benoitbenoit** [comment]
To be clear:
Index starts at j=0
It is OSA/ANSI indexing (not Noll)

**Comment by Giabbas** [comment]
Thank you very much, you have been really helpful!
Best
